{
 "PRed":[
  {
   "PR":{
    "__lazy_json__":"pr_json/265472086.json"
   },
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"0.6.1"
   },
   "keys":[
    "bot_rerun",
    "migrator_name",
    "migrator_version",
    "version"
   ]
  }
 ],
 "bad":{
  "exception":"<class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
  "traceback":[
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 421, in _make_request",
   "    six.raise_from(e, None)",
   "  File \"<string>\", line 3, in raise_from",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 416, in _make_request",
   "    httplib_response = conn.getresponse()",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/http/client.py\", line 1322, in getresponse",
   "    response.begin()",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/http/client.py\", line 303, in begin",
   "    version, status, reason = self._read_status()",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/http/client.py\", line 264, in _read_status",
   "    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/socket.py\", line 669, in readinto",
   "    return self._sock.recv_into(b)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py\", line 326, in recv_into",
   "    raise timeout(\"The read operation timed out\")",
   "socket.timeout: The read operation timed out",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/requests/adapters.py\", line 439, in send",
   "    resp = conn.urlopen(",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 719, in urlopen",
   "    retries = retries.increment(",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/util/retry.py\", line 400, in increment",
   "    raise six.reraise(type(error), error, _stacktrace)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/packages/six.py\", line 735, in reraise",
   "    raise value",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 665, in urlopen",
   "    httplib_response = self._make_request(",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 423, in _make_request",
   "    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/urllib3/connectionpool.py\", line 330, in _raise_timeout",
   "    raise ReadTimeoutError(",
   "urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/github3/models.py\", line 196, in _request",
   "    return request_method(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/requests/sessions.py\", line 546, in get",
   "    return self.request('GET', url, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/github3/session.py\", line 169, in request",
   "    response = super(GitHubSession, self).request(*args, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/requests/sessions.py\", line 533, in request",
   "    resp = self.send(prep, **send_kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/requests/sessions.py\", line 646, in send",
   "    r = adapter.send(request, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/requests/adapters.py\", line 529, in send",
   "    raise ReadTimeout(e, request=request)",
   "requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   "",
   "During handling of the above exception, another exception occurred:",
   "",
   "Traceback (most recent call last):",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.py\", line 659, in main",
   "    migrator_uid, pr_json = run(",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/auto_tick.py\", line 120, in run",
   "    feedstock_dir, repo = get_repo(",
   "  File \"/root/repo/cf-scripts/conda_forge_tick/git_utils.py\", line 111, in get_repo",
   "    repo = gh.repository(\"conda-forge\", feedstock_reponame)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/github3/github.py\", line 1981, in repository",
   "    json = self._json(self._get(url), 200)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/github3/models.py\", line 211, in _get",
   "    return self._request(\"get\", url, **kwargs)",
   "  File \"/opt/conda/envs/run_env/lib/python3.8/site-packages/github3/models.py\", line 201, in _request",
   "    raise exceptions.ConnectionError(exc)",
   "github3.exceptions.ConnectionError: <class 'requests.exceptions.ReadTimeout'>: A connection-level exception occurred: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=10)",
   ""
  ]
 },
 "conda-forge.yml":{},
 "feedstock_name":"tornado-sqlalchemy",
 "hash_type":"sha256",
 "meta_yaml":{
  "about":{
   "dev_url":"https://github.com/siddhantgoel/tornado-sqlalchemy",
   "doc_url":"https://tornado-sqlalchemy.readthedocs.io/",
   "home":"https://github.com/siddhantgoel/tornado-sqlalchemy",
   "license":"MIT",
   "license_family":"MIT",
   "license_file":null,
   "summary":"SQLAlchemy helpers for working in Tornado"
  },
  "build":{
   "noarch":"python",
   "number":"0",
   "script":" -m pip install . -vv"
  },
  "extra":{
   "recipe-maintainers":[
    "lincrosenbach",
    "kfasolin",
    "nicoddemus",
    "lincrosenbach",
    "kfasolin",
    "nicoddemus",
    "lincrosenbach",
    "kfasolin",
    "nicoddemus"
   ]
  },
  "package":{
   "name":"tornado-sqlalchemy",
   "version":"0.6.1"
  },
  "requirements":{
   "host":[
    "pip",
    "python >=3.5",
    "pip",
    "python >=3.5",
    "pip",
    "python >=3.5"
   ],
   "run":[
    "python >=3.5",
    "sqlalchemy >=1.0",
    "tornado >=4.0",
    "python >=3.5",
    "sqlalchemy >=1.0",
    "tornado >=4.0",
    "python >=3.5",
    "sqlalchemy >=1.0",
    "tornado >=4.0"
   ]
  },
  "source":{
   "sha256":"0d5d616a4edf4a01825a8e4acf7ff6b3c4192a1b49ca537da9a893a82bcb5b97",
   "url":"https://pypi.io/packages/source/t/tornado-sqlalchemy/tornado_sqlalchemy-0.6.1.tar.gz"
  },
  "test":{
   "imports":[
    "tornado_sqlalchemy",
    "tornado_sqlalchemy",
    "tornado_sqlalchemy"
   ]
  }
 },
 "name":"tornado-sqlalchemy",
 "new_version":"0.7.0",
 "pinning_version":"2019.03.17",
 "raw_meta_yaml":"{% set name = \"tornado-sqlalchemy\" %}\n{% set version = \"0.6.1\" %}\n\npackage:\n  name: \"{{ name|lower }}\"\n  version: \"{{ version }}\"\n\nsource:\n  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tornado_sqlalchemy-{{ version }}.tar.gz\n  sha256: 0d5d616a4edf4a01825a8e4acf7ff6b3c4192a1b49ca537da9a893a82bcb5b97\n\nbuild:\n  noarch: python\n  number: 0\n  script: \"{{ PYTHON }} -m pip install . -vv\"\n\nrequirements:\n  host:\n    - pip\n    - python >=3.5\n  run:\n    - python >=3.5\n    - sqlalchemy >=1.0\n    - tornado >=4.0\n\ntest:\n  imports:\n    - tornado_sqlalchemy\n\nabout:\n  home: https://github.com/siddhantgoel/tornado-sqlalchemy\n  license: MIT\n  license_family: MIT\n  license_file: \n  summary: SQLAlchemy helpers for working in Tornado\n  doc_url: https://tornado-sqlalchemy.readthedocs.io/\n  dev_url: https://github.com/siddhantgoel/tornado-sqlalchemy\n\nextra:\n  recipe-maintainers:\n    - lincrosenbach\n    - kfasolin\n    - nicoddemus\n",
 "req":{
  "__set__":true,
  "elements":[
   "pip",
   "python",
   "sqlalchemy",
   "tornado"
  ]
 },
 "smithy_version":"3.3.2",
 "url":"https://pypi.io/packages/source/t/tornado-sqlalchemy/tornado_sqlalchemy-0.6.1.tar.gz",
 "version":"0.6.1"
}