{
 "exception":"SHA256 mismatch: 'be8caaafe3ef2dc2c5ca02d8e91472bbdde0b19df1104170915fbb0b867c17a0' != 'f7dfeb1aaf7c723c7287e7c9a6978f2c7c4828a87bfa11d901b0f8c319a3b0ee'",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 347, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 69, in depfinder_audit_feedstock",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators/core.py\", line 68, in _get_source_code",
  "    return provide(md)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 654, in provide",
  "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 139, in unpack",
  "    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 105, in download_to_cache",
  "    (tp.upper(), hashed, expected_hash))",
  "RuntimeError: SHA256 mismatch: 'be8caaafe3ef2dc2c5ca02d8e91472bbdde0b19df1104170915fbb0b867c17a0' != 'f7dfeb1aaf7c723c7287e7c9a6978f2c7c4828a87bfa11d901b0f8c319a3b0ee'",
  ""
 ]
}