{
 "exception":"SHA256 mismatch: '35bd5a14434d0b4be3923417ff9cf1f81027d70e71ca56478a34df8c566d05eb' != 'f008f7e57ea0ed22e8ac292482069fb271ef3f747abbc58709f4da4cf956060f'",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 268, in main",
  "    deps = v[\"run\"](fctx, ctx, import_map)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 61, in depfinder_audit_feedstock",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators/core.py\", line 68, in _get_source_code",
  "    return provide(md)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 654, in provide",
  "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 139, in unpack",
  "    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 105, in download_to_cache",
  "    (tp.upper(), hashed, expected_hash))",
  "RuntimeError: SHA256 mismatch: '35bd5a14434d0b4be3923417ff9cf1f81027d70e71ca56478a34df8c566d05eb' != 'f008f7e57ea0ed22e8ac292482069fb271ef3f747abbc58709f4da4cf956060f'",
  ""
 ]
}