{
 "exception":"SHA256 mismatch: 'a8fa92d78543431ce6e31f3900654af5a3de64abc93da7af7c097089909d898b' != 'bec232215f7b9d3151268bf29708193de1b0abaf80f419dd3477e1a200edfc47'",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 385, in main",
  "    deps = v[\"run\"](fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 77, in depfinder_audit_feedstock",
  "    return extract_deps_from_source(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 59, in extract_deps_from_source",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/utils.py\", line 885, in _get_source_code",
  "    return provide(md)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 654, in provide",
  "    timeout=metadata.config.timeout, locking=metadata.config.locking)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 139, in unpack",
  "    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/source.py\", line 105, in download_to_cache",
  "    (tp.upper(), hashed, expected_hash))",
  "RuntimeError: SHA256 mismatch: 'a8fa92d78543431ce6e31f3900654af5a3de64abc93da7af7c097089909d898b' != 'bec232215f7b9d3151268bf29708193de1b0abaf80f419dd3477e1a200edfc47'",
  ""
 ]
}