exception: "'content'"
traceback: ['Traceback (most recent call last):', '  File "/root/repo/cf-scripts/conda_forge_tick/audit.py",
    line 117, in main', '    deps = v["run"](fctx, ctx)', '  File "/root/repo/cf-scripts/conda_forge_tick/audit.py",
    line 48, in grayskull_audit_feedstock', '    "pypi", pkg_name, pkg_version, download=False,',
  '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/factory.py",
    line 23, in create_recipe', '    name, version, **kwargs', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 56, in __init__', '    super(PyPi, self).__init__(name=name, version=version)',
  '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/base_recipe.py",
    line 58, in __init__', '    self.update_all_recipe()', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/base/base_recipe.py",
    line 112, in update_all_recipe', '    self.refresh_section(section)', '  File
    "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 499, in refresh_section', '    metadata = self._get_metadata()', '  File
    "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 524, in _get_metadata', '    license_metadata = PyPi._discover_license(metadata)',
  '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/pypi/pypi.py",
    line 614, in _discover_license', '    license_name_metadata=metadata.get("license"),',
  '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/license/discovery.py",
    line 193, in search_license_file', '    github_license = search_license_api_github(git_url,
    version, license_name_metadata)', '  File "/opt/conda/envs/run_env/lib/python3.7/site-packages/grayskull/license/discovery.py",
    line 223, in search_license_api_github', '    license_content = base64.b64decode(json_content["content"]).decode("utf-8")',
  "KeyError: 'content'", '']
