exception: invalid syntax (<string>, line 1)
traceback: ['Traceback (most recent call last):', '  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py",
    line 475, in main', '    deps = v["run"](fctx, ctx)', '  File "/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/audit.py",
    line 94, in grayskull_audit_feedstock', '    recipe = GrayskullFactory.create_recipe(',
  '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/base/factory.py",
    line 22, in create_recipe', '    return GrayskullFactory.REGISTERED_CLASS[repo_type.lower()](',
  '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 58, in __init__', '    super(PyPi, self).__init__(name=name, version=str(version)
    if version else None)', '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/base/base_recipe.py",
    line 58, in __init__', '    self.update_all_recipe()', '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/base/base_recipe.py",
    line 114, in update_all_recipe', '    self.refresh_section(section)', '  File
    "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 525, in refresh_section', '    metadata = self._get_metadata()', '  File
    "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 566, in _get_metadata', '    all_requirements = self._extract_requirements(metadata)',
  '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 789, in _extract_requirements', '    version_to_selector = PyPi.py_version_to_selector(',
  '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 1052, in py_version_to_selector', '    return PyPi._generic_py_ver_to(',
  '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 993, in _generic_py_ver_to', '    py_ver_enabled = PyPi._get_py_version_available(',
  '  File "/usr/share/miniconda/envs/run_env/lib/python3.8/site-packages/grayskull/pypi/pypi.py",
    line 1081, in _get_py_version_available', '    py_ver_enabled[sup_py] = eval(',
  '  File "<string>", line 1', '    sup_py = PyVer(int(3), int(6))', '           ^',
  'SyntaxError: invalid syntax', '']
