{
  "done": [
    "arrow-cpp",
    "turbodbc",
    "r-arrow",
    "omniscidb"
  ],
  "in-pr": [
    "snowflake-connector-python"
  ],
  "awaiting-pr": [],
  "not-solvable": [],
  "awaiting-parents": [],
  "bot-error": [
    "perspective"
  ],
  "_feedstock_status": {
    "arrow-cpp": {
      "num_descendants": 8,
      "immediate_children": [
        "mapd-core-cpu",
        "omniscidb",
        "omniscidb-cpu",
        "perspective",
        "pyarrow",
        "r-arrow",
        "snowflake-connector-python",
        "turbodbc"
      ],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/arrow-cpp-feedstock",
      "pr_status": null
    },
    "turbodbc": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/turbodbc-feedstock/pull/47",
      "pr_status": "unknown"
    },
    "snowflake-connector-python": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/snowflake-connector-python-feedstock/pull/55",
      "pr_status": "unstable"
    },
    "r-arrow": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/r-arrow-feedstock/pull/28",
      "pr_status": "unstable"
    },
    "omniscidb": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "",
      "pr_url": "https://github.com/conda-forge/omniscidb-feedstock",
      "pr_status": null
    },
    "perspective": {
      "num_descendants": 0,
      "immediate_children": [],
      "pre_pr_migrator_status": "bot error: master: Traceback (most recent call last):\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 953, in main\n    base_branch=base_branch,\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/auto_tick.py\", line 215, in run\n    timeout=300,\n  File \"/home/runner/work/autotick-bot/autotick-bot/cf-scripts/conda_forge_tick/utils.py\", line 99, in eval_cmd\n    c.check_returncode()\n  File \"/usr/share/miniconda/envs/run_env/lib/python3.7/subprocess.py\", line 444, in check_returncode\n    self.stderr)\nsubprocess.CalledProcessError: Command 'conda smithy rerender -c auto --no-check-uptodate' returned non-zero exit status 1.\n"
    }
  }
}