{
 "exception":"[Errno 2] No such file or directory: '/opt/conda/envs/run_env/conda-bld/astrometry_1588133374372/work/util/c.py'",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 68, in main",
  "    deps = audit_feedstock(fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 33, in audit_feedstock",
  "    deps = simple_import_search(cb_work_dir, remap=True)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/depfinder/main.py\", line 336, in simple_import_search",
  "    for mod, path, catcher in catchers:",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/depfinder/main.py\", line 295, in iterate_over_library",
  "    yield parse_file(full_file_path)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/depfinder/main.py\", line 262, in parse_file",
  "    with open(python_file, 'r') as f:",
  "FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/envs/run_env/conda-bld/astrometry_1588133374372/work/util/c.py'",
  ""
 ]
}