{
 "exception":"failed to parse packages from exception: The following specifications were found to be incompatible with each other:\n\nOutput in format: Requested package -> Available versions\n\nPackage setuptools conflicts for:\npyyaml -> cython -> setuptools\npython=3.7 -> pip -> setuptools\nsetuptools\n\nPackage python conflicts for:\npyyaml -> python_abi=3.8[build=*_cp38] -> python[version='3.7.*|3.8.*']\npyyaml -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']\nboost=1.63 -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']\nboost=1.63 -> numpy=1.12 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']\npython=3.7\nnumpy=1.11 -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0']\n\nPackage pypy3.6 conflicts for:\nsetuptools -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*']\nnumpy=1.11 -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.0.*|7.3.1.*']\npyyaml -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|>=7.3.1']\nboost=1.63 -> python=3.6 -> pypy3.6[version='7.3.0.*|7.3.1.*']\n\nPackage openssl conflicts for:\nnumpy=1.11 -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']\ncmake -> libcurl[version='>=7.64.1,<8.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2p,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']\nboost=1.63 -> python=3.6 -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']\npyyaml -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']\nsetuptools -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']\npython=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a']\n\nPackage _openmp_mutex conflicts for:\npython=3.7 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']\npyyaml -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']\ncmake -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']\nnumpy=1.11 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='*|>=4.5',build=*_llvm]\n\nPackage python_abi conflicts for:\nsetuptools -> python_abi[version='3.6.*|3.6|3.8.*|3.7.*',build='*_pypy36_pp73|*_cp38|*_cp36m|*_cp37m']\nsetuptools -> certifi[version='>=2016.9.26'] -> python_abi=2.7[build=*_cp27mu]\n\nPackage numpy conflicts for:\nboost=1.63 -> numpy[version='1.11.*|1.12.*']\nnumpy=1.11",
 "traceback":[
  "Traceback (most recent call last):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/environ.py\", line 764, in get_install_actions",
  "    actions = install_actions(prefix, index, specs, force=True)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/common/io.py\", line 88, in decorated",
  "    return f(*args, **kwds)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/plan.py\", line 474, in install_actions",
  "    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/core/solve.py\", line 117, in solve_for_transaction",
  "    should_retry_solve)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/core/solve.py\", line 158, in solve_for_diff",
  "    force_remove, should_retry_solve)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/core/solve.py\", line 281, in solve_final_state",
  "    ssc = self._run_sat(ssc)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/common/io.py\", line 88, in decorated",
  "    return f(*args, **kwds)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/core/solve.py\", line 808, in _run_sat",
  "    should_retry_solve=ssc.should_retry_solve",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/common/io.py\", line 88, in decorated",
  "    return f(*args, **kwds)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/resolve.py\", line 1318, in solve",
  "    self.find_conflicts(specs, specs_to_add, history_specs)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda/resolve.py\", line 351, in find_conflicts",
  "    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)",
  "conda.exceptions.UnsatisfiableError: The following specifications were found to be incompatible with each other:",
  "",
  "Output in format: Requested package -> Available versions",
  "",
  "Package setuptools conflicts for:",
  "pyyaml -> cython -> setuptools",
  "python=3.7 -> pip -> setuptools",
  "setuptools",
  "",
  "Package python conflicts for:",
  "pyyaml -> python_abi=3.8[build=*_cp38] -> python[version='3.7.*|3.8.*']",
  "pyyaml -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']",
  "boost=1.63 -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']",
  "boost=1.63 -> numpy=1.12 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']",
  "python=3.7",
  "numpy=1.11 -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0']",
  "",
  "Package pypy3.6 conflicts for:",
  "setuptools -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*']",
  "numpy=1.11 -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.0.*|7.3.1.*']",
  "pyyaml -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|>=7.3.1']",
  "boost=1.63 -> python=3.6 -> pypy3.6[version='7.3.0.*|7.3.1.*']",
  "",
  "Package openssl conflicts for:",
  "numpy=1.11 -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "cmake -> libcurl[version='>=7.64.1,<8.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2p,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']",
  "boost=1.63 -> python=3.6 -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "pyyaml -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "setuptools -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a']",
  "",
  "Package _openmp_mutex conflicts for:",
  "python=3.7 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']",
  "pyyaml -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']",
  "cmake -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']",
  "numpy=1.11 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='*|>=4.5',build=*_llvm]",
  "",
  "Package python_abi conflicts for:",
  "setuptools -> python_abi[version='3.6.*|3.6|3.8.*|3.7.*',build='*_pypy36_pp73|*_cp38|*_cp36m|*_cp37m']",
  "setuptools -> certifi[version='>=2016.9.26'] -> python_abi=2.7[build=*_cp27mu]",
  "",
  "Package numpy conflicts for:",
  "boost=1.63 -> numpy[version='1.11.*|1.12.*']",
  "numpy=1.11",
  "",
  "During handling of the above exception, another exception occurred:",
  "",
  "Traceback (most recent call last):",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 68, in main",
  "    deps = audit_feedstock(fctx, ctx)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/audit.py\", line 30, in audit_feedstock",
  "    cb_work_dir = _get_source_code(recipe_dir)",
  "  File \"/root/repo/cf-scripts/conda_forge_tick/migrators/core.py\", line 68, in _get_source_code",
  "    md = render(recipe_dir, config=Config(**CB_CONFIG))",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/api.py\", line 52, in render",
  "    bypass_env_check=bypass_env_check):",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 2054, in get_output_metadata_set",
  "    bypass_env_check=bypass_env_check)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/metadata.py\", line 727, in finalize_outputs_pass",
  "    permit_unsatisfiable_variants=permit_unsatisfiable_variants)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/render.py\", line 538, in finalize_metadata",
  "    exclude_pattern)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/render.py\", line 390, in add_upstream_pins",
  "    permit_unsatisfiable_variants, exclude_pattern)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/render.py\", line 378, in _read_upstream_pin_files",
  "    permit_unsatisfiable_variants=permit_unsatisfiable_variants)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/render.py\", line 154, in get_env_dependencies",
  "    channel_urls=tuple(m.config.channel_urls))",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/environ.py\", line 766, in get_install_actions",
  "    raise DependencyNeedsBuildingError(exc, subdir=subdir)",
  "  File \"/opt/conda/envs/run_env/lib/python3.7/site-packages/conda_build/exceptions.py\", line 78, in __init__",
  "    \" {}\".format(str(conda_exception)))",
  "RuntimeError: failed to parse packages from exception: The following specifications were found to be incompatible with each other:",
  "",
  "Output in format: Requested package -> Available versions",
  "",
  "Package setuptools conflicts for:",
  "pyyaml -> cython -> setuptools",
  "python=3.7 -> pip -> setuptools",
  "setuptools",
  "",
  "Package python conflicts for:",
  "pyyaml -> python_abi=3.8[build=*_cp38] -> python[version='3.7.*|3.8.*']",
  "pyyaml -> python[version='2.7.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.4.*']",
  "boost=1.63 -> python[version='2.7.*|3.5.*|3.6.*|3.4.*']",
  "boost=1.63 -> numpy=1.12 -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']",
  "python=3.7",
  "numpy=1.11 -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0']",
  "",
  "Package pypy3.6 conflicts for:",
  "setuptools -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*']",
  "numpy=1.11 -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.0.*|7.3.1.*']",
  "pyyaml -> python[version='>=3.6,<3.7.0a0'] -> pypy3.6[version='7.3.*|7.3.0.*|7.3.1.*|>=7.3.1']",
  "boost=1.63 -> python=3.6 -> pypy3.6[version='7.3.0.*|7.3.1.*']",
  "",
  "Package openssl conflicts for:",
  "numpy=1.11 -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "cmake -> libcurl[version='>=7.64.1,<8.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a|>=1.0.2p,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a']",
  "boost=1.63 -> python=3.6 -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "pyyaml -> python[version='>=3.8,<3.9.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "setuptools -> python[version='>=3.6,<3.7.0a0'] -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1g,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']",
  "python=3.7 -> openssl[version='>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.1.1b,<1.1.2a']",
  "",
  "Package _openmp_mutex conflicts for:",
  "python=3.7 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']",
  "pyyaml -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']",
  "cmake -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']",
  "numpy=1.11 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='*|>=4.5',build=*_llvm]",
  "",
  "Package python_abi conflicts for:",
  "setuptools -> python_abi[version='3.6.*|3.6|3.8.*|3.7.*',build='*_pypy36_pp73|*_cp38|*_cp36m|*_cp37m']",
  "setuptools -> certifi[version='>=2016.9.26'] -> python_abi=2.7[build=*_cp27mu]",
  "",
  "Package numpy conflicts for:",
  "boost=1.63 -> numpy[version='1.11.*|1.12.*']",
  "numpy=1.11",
  ""
 ]
}